=== ashlanderDesign/isaevd-wishlist/data/table.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Product",
  "description": "Описание товара",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Название товара"
      },
      "priority": {
        "type": "integer",
        "minimum": 0,
        "maximum": 10,
        "description": "Приоритет товара"
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Теги товара"
      },
      "price": {
        "type": "number",
        "minimum": 0,
        "description": "Цена товара"
      },
      "link": {
        "type": "string",
        "format": "uri",
        "description": "Ссылка на товар"
      },
      "isReceived": {
        "type": "boolean",
        "description": "Получен ли товар"
      }
    },
    "required": ["name", "priority", "tags", "price", "link", "isReceived"]
  }
}

=== ashlanderDesign/isaevd-wishlist/data/table.json
[
  {
    "name": "Samsung Galaxy S23 256Gb",
    "priority": 10,
    "tags": ["Техника"],
    "price": 70000,
    "link": "https://www.dns-shop.ru/product/734f8ff2fbb8bfcd/61-smartfon-samsung-galaxy-s23-256-gb-cernyj/",
    "isReceived": false
  },
  {
    "name": "Apple AirPods 2 USB-C",
    "priority": 9,
    "tags": ["Техника"],
    "price": 21000,
    "link": "https://biggeek.ru/products/apple-airpods-pro-2nd-generation-with-magsafe-charging-case-usb-c",
    "isReceived": false
  },
  {
    "name": "Apple MacBook Pro 14 M3 8/512GB",
    "priority": 8,
    "tags": ["Техника"],
    "price": 170000,
    "link": "https://biggeek.ru/products/apple-macbook-pro-14-mtl73-space-gray-m3-8-core-gpu-10-core-8gb-512gb",
    "isReceived": false
  },
  {
    "name": "Книга игрока D&D",
    "priority": 8,
    "tags": ["Книги", "Для D&D"],
    "price": 4490,
    "link": "https://hobbygames.ru/dungeons-and-dragons-kniga-igroka",
    "isReceived": false
  },
  {
    "name": "Карты заклинаний: Мистическая магия",
    "priority": 8,
    "tags": ["Для D&D"],
    "price": 2490,
    "link": "https://hobbygames.ru/dungeons-and-dragons-karti-zaklinanij-misticheskaja-magija",
    "isReceived": false
  },
  {
    "name": "Nintendo Switch rev.2 (под прошивку)",
    "priority": 8,
    "tags": ["Техника", "Для игр"],
    "price": 25000,
    "link": "https://market.yandex.ru/cc/8EqhHRN",
    "isReceived": false
  },
  {
    "name": "Steam Deck",
    "priority": 8,
    "tags": ["Техника", "Для игр"],
    "price": 60000,
    "link": "https://market.yandex.ru/cc/tzUdOp2",
    "isReceived": false
  },
  {
    "name": "Геймпад Flydigi Vader 3 Pro",
    "priority": 7,
    "tags": ["Техника", "Для игр"],
    "price": 5600,
    "link": "https://ozon.ru/t/lY2ZlMk",
    "isReceived": false
  },
  {
    "name": "Рюкзак XD Design Bobby Hero Regular",
    "priority": 7,
    "tags": ["Аксессуары"],
    "price": 18000,
    "link": "https://re-store.ru/catalog/P705.291/",
    "isReceived": false
  },
  {
    "name": "Умная колонка Яндекс Станция Макс с Zigbee",
    "priority": 7,
    "tags": ["Техника", "Умный дом"],
    "price": 34000,
    "link": "https://market.yandex.ru/cc/N6sAwr2",
    "isReceived": false
  },
  {
    "name": "Apple Watch SE 2022 44mm",
    "priority": 6,
    "tags": ["Техника"],
    "price": 32000,
    "link": "https://www.dns-shop.ru/product/e682c4eb3014ed20/smart-casy-apple-watch-se-2022-44mm/",
    "isReceived": false
  },
  {
    "name": "Microsoft Xbox Series X",
    "priority": 6,
    "tags": ["Техника", "Для игр"],
    "price": 55000,
    "link": "https://www.dns-shop.ru/product/de3881f3d7dfed20/igrovaa-konsol-microsoft-xbox-series-x/",
    "isReceived": false
  },
  {
    "name": "Sony Playstation 5",
    "priority": 6,
    "tags": ["Техника", "Для игр"],
    "price": 60000,
    "link": "https://www.dns-shop.ru/product/9006a22a3888ed20/igrovaa-konsol-playstation-5/",
    "isReceived": false
  },
  {
    "name": "Руль ThrustMaster T150 Force Feedback",
    "priority": 6,
    "tags": ["Техника", "Для игр"],
    "price": 27000,
    "link": "https://www.dns-shop.ru/product/a9f6cf522df93330/rul-thrustmaster-t150-force-feedback-cernyj/",
    "isReceived": false
  },
  {
    "name": "[4X] be quiet! SILENT WINGS PRO 4 PWM",
    "priority": 6,
    "tags": ["Комплектующие для ПК"],
    "price": 18000,
    "link": "https://www.dns-shop.ru/product/369b4ae9010ded20/ventilator-be-quiet-silent-wings-pro-4-pwm-bl098/",
    "isReceived": false
  },
  {
    "name": "Монитор Samsung S27AG520PI",
    "priority": 5,
    "tags": ["Техника"],
    "price": 32000,
    "link": "https://www.dns-shop.ru/product/1b4d4dbfade8ed20/27-monitor-samsung-s27ag520pi-cernyj/",
    "isReceived": false
  },
  {
    "name": "Медиаплеер Apple TV 4K",
    "priority": 5,
    "tags": ["Техника", "Умный дом"],
    "price": 22000,
    "link": "https://www.dns-shop.ru/product/16bbdc51600ced20/mediapleer-apple-tv-4k-mn893paa",
    "isReceived": false
  },
  {
    "name": "iPad Mini 2021 64Gb + Apple Pencil",
    "priority": 10,
    "tags": ["Техника"],
    "price": 70000,
    "link": "https://www.dns-shop.ru/product/163be9b7dc01ed20/83-planset-apple-ipad-mini-2021-wi-fi-64-gb-seryj",
    "isReceived": true
  },
  {
    "name": "A-Data XPG GAMMIX D20 (32GB)",
    "priority": 10,
    "tags": ["Комплектующие для ПК"],
    "price": 7000,
    "link": "https://www.dns-shop.ru/product/028eddb6ea99d763/operativnaa-pamat-a-data-xpg-gammix-d20-ax4u320016g16a-dcbk20-32-gb/",
    "isReceived": true
  },
  {
    "name": "nVIDIA GeForce RTX 4060 Ti 16GB",
    "priority": 10,
    "tags": ["Комплектующие для ПК"],
    "price": 52000,
    "link": "https://www.dns-shop.ru/product/67540c757e24ed20/videokarta-gigabyte-geforce-rtx-4060-ti-windforce-oc-gv-n406twf2oc-16gd",
    "isReceived": true
  },
  {
    "name": "Meta Quest 2",
    "priority": 10,
    "tags": ["Техника", "Для игр"],
    "price": 40000,
    "link": "https://www.dns-shop.ru/product/5fd76980e7a6ed20/sistema-virtualnoj-realnosti-oculus-quest-2-belyj/",
    "isReceived": true
  },
  {
    "name": "The Elder Scrolls V: Skyrim VR",
    "priority": 9,
    "tags": ["Видеоигры"],
    "price": 1500,
    "link": "https://store.steampowered.com/app/611670/",
    "isReceived": true
  },
  {
    "name": "AMD Ryzen 5 5500",
    "priority": 9,
    "tags": ["Комплектующие для ПК"],
    "price": 8000,
    "link": "https://www.dns-shop.ru/product/2779e1d6afeced20/processor-amd-ryzen-5-5500-oem/",
    "isReceived": true
  },
  {
    "name": "Книга мастера D&D",
    "priority": 8,
    "tags": ["Книги", "Для D&D"],
    "price": 4490,
    "link": "https://hobbygames.ru/dungeons-andamp-dragons-rukovodstvo-mastera-podzemelij",
    "isReceived": true
  },
  {
    "name": "Графический планшет",
    "priority": 8,
    "tags": ["Техника", "Для рисования"],
    "price": 6000,
    "link": "https://www.dns-shop.ru/product/621b21ec50a7ed20/graficeskij-planset-wacom-one-by-wacom-2-medium/",
    "isReceived": true
  },
  {
    "name": "Крепление для мониторов ONKRON G200",
    "priority": 7,
    "tags": ["Техника"],
    "price": 11500,
    "link": "https://www.dns-shop.ru/product/c2f0d326f8dec823/kreplenie-dla-monitorov-onkron-g200/",
    "isReceived": true
  },
  {
    "name": "Игровой движок. Программирование и внутреннее устройство",
    "priority": 6,
    "tags": ["Книги"],
    "price": 5000,
    "link": "https://www.chitai-gorod.ru/product/igrovoy-dvizhok-programmirovanie-i-vnutrennee-ustroystvo-2825633",
    "isReceived": true
  },
  {
    "name": "Кресло игровое ZONE 51 ARENA PRO",
    "priority": 5,
    "tags": ["Мебель"],
    "price": 17000,
    "link": "https://market.yandex.ru/cc/DET3M3o",
    "isReceived": true
  },
  {
    "name": "Redragon Dragonwarrior",
    "priority": 4,
    "tags": ["Комплектующие для ПК"],
    "price": 7490,
    "link": "https://www.dns-shop.ru/product/073a812b9538ed20/klaviatura-besprovodnaa-provodnaa-redragon-dragonwarrior-70520/",
    "isReceived": true
  }
]
